version: '3'
services:
  ui:
    build: 
      dockerfile: Dockerfile
      context: ./ui
    image: bittap_app_image
    container_name: bittap_app_container
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - backend

  api:
    build: 
      dockerfile: Dockerfile
      context: ./api
    image: "bittap-api"
    container_name: "bittap-api"
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules 
      - ./:/usr/src/app
    networks:
      - backend

  webserver:
    container_name: bittap_nginx_container
    image: nginx:latest
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./nginx:/etc/nginx/conf.d/default.conf
    networks: 
      backend

volumes:
  node_modules:  

networks:
  backend:
    driver: bridge