version: '3'

services:
  api:
    build: .
    image: nodejs
    container_name: nodejs
    restart: always
    env_file: .env
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB 
    expose:
      - "8080"
    ports:
      - "8080:8080"
    # depends_on: 
    #   - db
    volumes:
      - ./:/usr/src/app
    networks:
      - backend

  # db:
  #   image: mongo:4.1.8-xenial
  #   container_name: db
  #   restart: always
  #   env_file: .env
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    # volumes:  
    #   - dbdata:/data/db   
    # networks:
    #   - backend 
    # ports:
    #   - "27017:27017"

volumes:
  # dbdata: 
  node_modules:  

networks:
  backend:
    driver: bridge