version: '3'

services:
    ui: 
        build: ./ui
        volumes: 
            - ./ui:/app
        networks:
            - app-network
        ports:
            - "3000:3000"

    api:
        build: ./api
        volumes:
            - ./api:/app
        ports:
          - '5000:5000'
        networks:
        - app-network
        
networks:
    app-network: