version: '3'
services:
  api:
    container_name: development_api
    build: 
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /app/node_modules 
      - ./api:/app
    expose:
      - '8081'
    ports: 
      - '8081:8081'

  nginx:
    container_name: development_nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    expose: 
      - '80'
    ports: 
      - '80:80'
    depends_on:
      - api
      - ui
    
  ui:
    container_name: development_ui
    build: 
      dockerfile: Dockerfile
      context: ./ui
    volumes:
      - /app/node_modules 
      - ./ui:/app
    expose:
      - '3000'
    ports: 
      - '3000:3000'
