version: '3'
services:
  ui:
    build: 
      dockerfile: Dockerfile
      context: ./ui
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - ./ui:/app
    networks:
      - backend

  api:
    build: 
      dockerfile: Dockerfile
      context: ./api
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules 
      - ./:/usr/src/app
    networks:
      - backend

  webserver:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
      - "443:443"
      - '5000:80'
    networks: 
      - backend

volumes:
  node_modules:  

networks:
  backend:
    driver: bridge