//VALIDATE EMAIL, VALIDATE PASSWORD, VALIDATE CONFIRM PASSWORD, 
export const VALIDATE_EMAIL_REGISTER = "VALIDATE_EMAIL_REGISTER";
export const VALIDATE_PASSWORD_REGISTER = "VALIDATE_PASSWORD_REGISTER";
export const VALIDATE_CONFRIMPASSWORD_REGISTER = "VALIDATE_CONFRIMPASSWORD_REGISTER";
export const ENABLE_REGISTER_BUTTON = "ENABLE_REGISTER_BUTTON";
